CREATE PROCEDURE SALES.TOTAL_REVENUE(IN S_MONTH INTEGER, IN S_YEAR INTEGER, OUT TOTAL DECIMAL(10,2))
PARAMETER STYLE JAVA READS SQL DATA LANGUAGE JAVA EXTERNAL NAME 
'com.github.marschall.springjdbccall.DerbyProcedureSources.calculateRevenueByMonth';

CREATE FUNCTION SALES.TAX(SUBTOTAL DOUBLE) RETURNS DOUBLE
PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA
EXTERNAL NAME 'com.github.marschall.springjdbccall.DerbyProcedureSources.tax'


