CREATE procedure plus1inout (IN arg int, OUT res int)
BEGIN ATOMIC
  SET res = arg + 1;
END
/;

CREATE FUNCTION an_hour_before (t TIMESTAMP)
   RETURNS TIMESTAMP
   RETURN t - 1 HOUR;
/;

CREATE FUNCTION array_cardinality (a INT ARRAY)
   RETURNS INT
   RETURN CARDINALITY(a);
/;

CREATE FUNCTION return_array ()
   RETURNS INT ARRAY
   RETURN SEQUENCE_ARRAY(0, 10, 5);
/;

CREATE FUNCTION one_two() 
RETURNS TABLE(id integer) 
READS SQL DATA BEGIN ATOMIC 
   RETURN TABLE(SELECT 1 FROM (VALUES(0)) UNION ALL SELECT 2 FROM (VALUES(0))); 
END 
/;



